### ISSUE TITLE
Spontanentnahme Geldeinzahlung

### ISSUE THREAD

**Issue by Chaosdelphin** [hftlclub/ng-iltis#114]
Es wird leider vom Frontend nicht zugelassen eine Spontanentnahme ohne Buchung von Getränken aber mit Geldeinzahlung zu machen. Ich musste heute schonwieder ein Bier trinken um Geld nachzuzahlen :/

**Comment by Chaosdelphin** [comment]
weil ich a) geld nachzahlen möchte, wenn ich mortag nicht genug cash für die spontanentnahme hatte oder b) trinkgeld einzahlen möchte....

**Comment by fmalcher** [comment]
a) Dann musst Du das Event offen lassen, bis Du bezahlt hast, oder das Event mit nem Betrag schließen, und den später einzahlen
b) Gehört nicht ins ILTIS (genauso wie andere Verleiheinnahmen). Stattdessen zusammen mit einem Einzahlungszettel in den Briefkasten

CC @rweisse @Leonard590

**Comment by Leonard590** [comment]
Was Ferdi sagt ;)

Die Einnahmen im Iltis sind nur dazu da, die verbrauchten Getränke mit dem eingenommenen Geld in Einklang zu bringen. Servicepauschalen (auch z.B. von PPs) gehören da nicht rein.

Der Fall (a) kommt offiziell nicht vor, da wir offiziell keine Getränke auf Pump rausgeben, sondern nur direkte Bezahlung akzeptieren. Bin auch der Meinung, dass dieser Sonderfall nicht abgefangen werden muss.
