### ISSUE TITLE
Add info area (Version of Frontend and Backend)

### ISSUE THREAD

**Issue by rweisse** [hftlclub/ng-iltis#53]
The info area should additionally show the git-commit-id for backend and frontend.

**Comment by fmalcher** [comment]
I think we should still stick with version numbers as they are the usual way of versioning software.
However, why not display both version number AND commit sha?

For the backend, I need that information in the `/info` resource, please ;-)

@rweisse

**Comment by rweisse** [comment]
Yep. Just created an issue for me :-P

**Comment by fmalcher** [comment]
https://github.com/hftlclub/node-iltis/issues/24

**Comment by rweisse** [comment]
`/info` will offer this information from know on.

**Comment by fmalcher** [comment]
done in  3305a269d1f4cb6950f667b2e6c1764a494d6630
