### ISSUE TITLE
New position for Management-Button

### ISSUE THREAD

**Issue by rweisse** [hftlclub/ng-iltis#56]
The management button in the topbar should switch to the right side.
![bildschirmfoto 2017-09-15 um 19 42 10](https://user-images.githubusercontent.com/7416092/30495920-2cc646b8-9a4e-11e7-8502-536ff7991300.png)

**Comment by fmalcher** [comment]
Yup, we can do this, but we'll have to see what it looks when there's the additional user data button (login, logout, username, etc.) in the top right corner
