### ISSUE TITLE
Inventory View for Event

### ISSUE THREAD

**Issue by rweisse** [hftlclub/ng-iltis#71]
The inventory view of an event should contain all information our papers got:
* Headline like 'Lagerbestand' or 'Abrechnung' etc (missing) 
* Event name + description (check)
* Date (check)
* Time (missing)
* Cash position before (missing)
* Cash position after (missing)

There should be a print button because nobody likes to search for the browsers print functionalities (not everyone in our team knows the command `ctrl+p`). And I think we need that button for the web applications view on our tablet.

**Comment by fmalcher** [comment]
IMO this is not the task of the inventory view.
We should introduce a new page like "printable event summary" for that
