### ISSUE TITLE
GUI Bug (Management View)

### ISSUE THREAD

**Issue by rweisse** [hftlclub/ng-iltis#72]
Steps to reproduce:
Click:
1. Verwaltung
2. Produkte
3. Verwaltung
4. Kategorien
5. ...

Everytime the new view is just added to the current one (it should be replaced): Scroll down to see what I mean.

**Comment by fmalcher** [comment]
![bildschirmfoto 2017-11-25 um 12 00 19](https://user-images.githubusercontent.com/1683147/33229873-39ccfe30-d1d8-11e7-8630-3bd87b8b10b7.png)

**Comment by fmalcher** [comment]
Interestingly, I cannot reproduce this with my local copy... seems to be a version issue

**Comment by fmalcher** [comment]
Reopened unitl definitely fixed

**Comment by fmalcher** [comment]
couldnt see the bug anymore now.
can you double check this please and close this issue, @rweisse ?
